name: Deploy to HubSpot

on:
  push:
    branches:
      - master  # or your deploy branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Upload to HubSpot
        run: hs project upload cms-react-app
        env:
          HUBSPOT_ACCOUNT_ID: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}